kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: home
networking:
  podSubnet: "10.200.0.0/16"
  serviceSubnet: "10.201.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP