apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infrastructure
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.6
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 1h0m0s
  values:
    controller:
      hostPort:
        enabled: true
      ingressClassResource:
        default: true
#      publishService:
#        enabled: false
      service:
        type: NodePort
      watchIngressWithoutClass: true