apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: infrastructure
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: 10.6.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 5m
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
    logs:
      general:
        level: INFO
      access:
        enabled: true