apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: infrastructure
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: 10.6.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 5m
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    hostNetwork: true
    ports:
      web:
        nodePort: 32080
    service:
      type: NodePort