apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  namespace: home
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: podinfo
                port:
                  number: 9898
#      host: "podinfo.home.arpa"