apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: home
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 5m