apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  interval: 1h0m0s