apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: home-assistant
  name: home-assistant
  namespace: home
spec:
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: home-assistant