apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: infrastructure
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 5m
  values:
    configInline:
      address-pools:
        - name: home
          protocol: layer2
          addresses:
            - 192.168.1.230-192.168.1.240