#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: mosquitto-config
#  namespace: home
#  labels:
#    app.kubernetes.io/name: mosquitto
#    app.kubernetes.io/part-of: mosquitto
#data:
#  mosquitto.conf: |-
#    log_type all
#    log_dest stderr
#
#    allow_anonymous false
#    password_file /home/mosquitto/passwd
#
#    listener 1883
#    protocol mqtt