apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: mosquitto
  name: mosquitto
  namespace: home
spec:
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: mqtt
    - name: mqtts
      port: 8883
      protocol: TCP
      targetPort: mqtts
  selector:
    app.kubernetes.io/name: mosquitto
