apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwd
  namespace: home
spec:
  encryptedData:
    passwd: AgAfKY8SCHor4xDlYCl4Weg1rh39pxXGG261TUHeHueXFd8osG4KBi2b2thZEcKfFi0auZNA/0Ir/sbnZDDxV8pVHw74PK6VgP7sYQJ0zOMds2oMbdpHptJj7vdcKVuXR5qdevDeQbIFsnOimPAEzkhsXRZZLCXWygvXDFpW11VZ9U0yhCawllgNRfYfrk6pM/56TqZakRFfCw04vyxWnv8a6uUB7PGCbSDEzl6AV5Xov3wpD1nIhgEuThqnOhviz8X+UmkZrZX4HGufbHifYvUeS8y6J3fHYt60b5PbE56wAgFeFLO7bf5rpaoZH7+zTUaNqBYp50fpwMeUOSG4KQieJK1T3N5VaAd6eFsCe8XusQ8mBlSy66kW7mZ93bDk8aeecO8SIc9ZWVidz4Y9HRcgEeTnKfJAcylz8H3L1b4QpFnD3LJm4T8548o2hOm8N/r0iXRHHQ4edE+I6XyIlEphw9ifdGVDHEy0ZF59ggZdlcdk03OsuepKu9toKW9TQ+ZpKyRCXeB8kQdz612vOIxIIM3aZCvdBJJ5MHATATpb3JRA39iaOO2B2SMF5RgSXJarbAxkys+sEtkZenaP+Qm3g7n1+oPTf0ICBDpwr5qQ2DqE9faNPE81b7/9GKwLEfW6QHcYeEVGjd7d/SWD1V5hEWkeVOZgobgh4k8k1/lx5CCGT82MJyEzkz/PeCKxf6Ota2MsaCDQ9i79VTkIYLPFtz5DaFd7PFkjmN39H8QJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mosquitto-passwd
      namespace: home

