apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwd
  namespace: home
spec:
  encryptedData:
    passwd: AgA90YW9G0y3RUmcD53ZdaUSSLitAgWuwrmhzwmdVwXyAQL6cVD+mSCRASXWE2Geo9AUyVuPErQsrrH6pNU0JLNBOa4iAXOIyrFrsflbaT3uWpFIsKf2kliTtYqFD9PjvX48BO0m+07n7X+8gI/GrhS+Qovpd8B1+r/NUQ02rJ6ag9qU9vDY0JYiaP8YlZY/0gZ305GnI3u/mWtVm4o53Rn/ZlRTllY7PtOUrGf3U8rFgjBzJBU5N4fbjT60dDoFO/1zxNUz4GfP8l0SbXtg5Qf4PjgxvnLmTdLFe8lVnnwU+522+ZOK62gpCLU8URclWeG73hUcXxpCBoZTVfc7Yfgb25tblKuWTl44JPXiEB+KIZKeyZY90xkZwBI4xx+BWYYccvQR8CpbdHgA/J87I3W9MVekyE7I5sPnLLjXCAacIOHaTT2vgh8Jr5gy2C7c88zUHgRUnqgPSyMUQ0X3yqlTlxdkN/VJe1z0qIAcyeF38MZAp8ysvRzhssN+9WrQ/8LjDJeNzWcjBTx4VHWwzlckmVO9Q1e4+1lZDOYJAVH6x628QeYIsqjeJQR/FI31bjPiZybX26Ba3FygClYSqxN4xuvwHwClo1EWfekub1RbYYMBT+LmZM6Q1v7N+mzoN8cbuAVL29U+fyOID1KkAEkVNOVOwPq0zIljdXe6uMXiZKSIi0zWUufzhtHHnpTEgrbKl4lHLJDLTzpRlUt0/mL21uDnp4GEaQODEByVPiu8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mosquitto-passwd
      namespace: home

