#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: mosquitto
#  namespace: home
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: test
#  labels:
#    app.kubernetes.io/name: mosquitto
#    app.kubernetes.io/part-of: mosquitto
#spec:
#  ingressClassName: traefik
#  rules:
#    - host: "mosquitto.home.arpa"
#      http:
#        paths:
#          - pathType: ImplementationSpecific
#            backend:
#              service:
#                name: mosquitto
#                port:
#                  number: 1883

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mosquitto-test
  namespace: home
spec:
  entryPoints:
    - test
  routes:
    - match: Host(`mosquitto.home.arpa`)
      kind: Rule
      services:
        - name: mosquitto
          port: 1883