#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: grafana
#  namespace: home
#spec:
#  releaseName: grafana
#  chart:
#    spec:
#      chart: grafana
#      version: 6.18.1
#      sourceRef:
#        kind: HelmRepository
#        name: grafana
#        namespace: flux-system
#  interval: 5m
#  values:
#    admin:
#      existingSecret: grafana-auth
##    datasources:
##      datasources.yaml:
##        apiVersion: 1
##        datasources:
##          - name: InfluxDB
##            type: influxdb
##            orgId: 1
##            url: influxdb.home.svc
##            user: influxdb-read
##            database: home_assistant
##            withCredentials: true
##            isDefault: false
##            version: 1
##            editable: false
##            secureJsonData:
##              password: ${INFLUXDBHA_READ_USER_PASSWORD}
#    ingress:
#      enabled: true
#      ingressClassName: traefik
#      hosts:
#        - grafana.home.arpa