apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home
  labels:
    app.kubernetes.io/name: zigbee2mqtt
    app.kubernetes.io/part-of: zigbee2mqtt
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zigbee2mqtt
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.22.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Europe/Dublin
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
              valueFrom:
                secretKeyRef:
                  name: zigbee2mqtt-secret
                  key: network-key
            - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: zigbee2mqtt-secret
                  key: mqtt-user
            - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zigbee2mqtt-secret
                  key: mqtt-password
          volumeMounts:
            - mountPath: /app/data/configuration.yaml
              name: configuration
              subPath: configuration.yaml
      volumes:
        - name: configuration
          configMap:
            name: zigbee2mqtt-config
            items:
              - key: configuration.yaml
                path: configuration.yaml