#apiVersion: v1
#kind: Service
#metadata:
#  name: postgresql
#  namespace: home
#  labels:
#    app.kubernetes.io/name: postgresql
#    app.kubernetes.io/part-of: postgresql
#spec:
#  ports:
#    - port: 5432
#      name: postgresql
#  selector:
#    app.kubernetes.io/name: postgresql